import Head from 'next/head'
import { getVgg, setVgg } from '../../'


export default function Home() {
  return (
    <>
      <Head>
        <title>VggSdk Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  )
}

getVgg().then((vgg) => {
  console.debug('#vgg is: ', vgg);
});

setVgg({ foo: "bar" })

getVgg().then((vgg) => {
  console.debug('#vgg is: ', vgg);
});