import Head from 'next/head'
import { getVgg, setVgg, DesignDocument } from '../../'


export default function Home() {
  return (
    <>
      <Head>
        <title>VggSdk Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  )
}

function test0() {
  getVgg().then((vgg) => {
    console.debug('#vgg is: ', vgg);
  });

  setVgg({ foo: "bar" })

  getVgg().then((vgg) => {
    console.debug('#vgg is: ', vgg);
  });
}

async function test1() {
  // Given
  const sut = await DesignDocument.getDesignDocument();

  // When
  sut.a.b.c.d.k1 = 1;

  // Then
  console.log(sut.a.b.c.d);
}

test1();